# Generated by Django 4.0 on 2021-12-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usertext_number_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertext',
            name='text_message',
        ),
    ]
